// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/30/2025, 12:48:01 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/bfadiguzel/work/todo/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bfadiguzel/work/todo/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bfadiguzel/work/todo/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bfadiguzel/work/todo/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bfadiguzel/work/todo/frontend/plugins/**/*.{js,ts,mjs}","/Users/bfadiguzel/work/todo/frontend/composables/**/*.{js,ts,mjs}","/Users/bfadiguzel/work/todo/frontend/utils/**/*.{js,ts,mjs}","/Users/bfadiguzel/work/todo/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bfadiguzel/work/todo/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/bfadiguzel/work/todo/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/bfadiguzel/work/todo/frontend/app.config.{js,ts,mjs}","/Users/bfadiguzel/work/todo/frontend/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;